---
- name: Create fragments.d directory
  file:
    path: /etc/pacman.d/fragments.d
    state: directory
    owner: root
    group: root

- name: Copy 10-core.conf
  template:
    src: 10-core.conf.j2
    dest: /etc/pacman.d/fragments.d/10-core.conf
    owner: root
    group: root
    mode: 0644
  notify: rebuild pacman.conf

- name: Force flush handlers to rebuild pacman.conf
  meta: flush_handlers
